### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by clburlison** [ygini/ygini-recipes#1]
Hey Yoann,

I really recommend checking out [Recipe Robot](https://github.com/homebysix/recipe-robot) by Elliot. It is really useful for individuals who are new the AutoPkg community. As Greg already pointed out the [Guidelines](https://github.com/autopkg/autopkg/wiki/Sharing-Recipes) for sharing-recipes are also useful.

Since you are releasing on Github all you need to do is pass the following URL, https://github.com/ygini/Hello-IT, into Recipe Robot and it can create the `.download`, `.pkg`, `.munki` & `.install` recipes for you. 

Hope that helps,
Clayton

**Comment by ygini** [comment]
Maybe I've already read the guidelines?

What's the problem in fact with my repo?

**Comment by clburlison** [comment]
There isn't any _wrong_ with the repo. Your recipes run perfectly fine as they are. I would _recommend_ adding the `.pkg` and `.install` recipes as they are nice. However other than that if you wanted to merge these into the main autopkg group I don't see anything that would stop the merge. 

I mostly wanted to make you aware of Recipe Robot as it's still pretty new.

**Comment by ygini** [comment]
OK, thanks for the info, I will consider adding the .pkg and .install scenario even if I don't really find them useful…
